### ISSUE TITLE
add api send message

### ISSUE THREAD

**Issue by diazzaid** [viniciusgdr/viniciusbot-md-public#1]
hai.. how to add interface api for send message

**Comment by viniciusgdr** [comment]
hi,  I don't use API Interface for Baileys, you probably won't need to change many things if you already have it, edit it any way you like using this base as an "example"

**Comment by diazzaid** [comment]
> hi, I don't use API Interface for Baileys, you probably won't need to change many things if you already have it, edit it any way you like using this base as an "example"

yes because I don't understand how to add api in this md version😀,
 it works on single device mode

**Comment by viniciusgdr** [comment]
> > hi, I don't use API Interface for Baileys, you probably won't need to change many things if you already have it, edit it any way you like using this base as an "example"
> 
> yes because I don't understand how to add api in this md version😀, it works on single device mode

try to change the connection way and use as the this base, i uploaded now the correction of 2 errors. 🙃
